name: Update README TOC

on:
  push:
    paths:
      - "README.md"
  schedule:
    - cron: "0 2 * * *" # daily at 02:00 UTC

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip

      - name: Generate TOC and commit
        run: |
          python .github/scripts/generate_toc.py README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "chore: update README TOC [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
