name: Update README TOC

on:
  push:
    paths:
      - "README.md"
  schedule:
    - cron: "0 2 * * *" # daily at 02:00 UTC

jobs:
  update-toc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip

      - name: Generate units table and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/generate_units_table.py README.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "chore: update README units table [skip ci]" || echo 'nothing to commit'
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
